# Project Title
## Personalized Medical Recommendation System

## Importing Required Libraries

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
import os
import sys

os.environ['PYTHON_HOME'] = sys.executable
os.environ['PYTHON_DRIVER_HOME'] = sys.executable
os.environ['JAVA_HOME'] = r'D:\Java'

## Loading the Dataset

In [3]:
import pandas as pd

In [4]:
dataset = pd.read_csv('Training.csv')

In [5]:
df = dataset

In [6]:
df.isnull().sum()

itching                 0
skin_rash               0
nodal_skin_eruptions    0
continuous_sneezing     0
shivering               0
                       ..
inflammatory_nails      0
blister                 0
red_sore_around_nose    0
yellow_crust_ooze       0
prognosis               0
Length: 133, dtype: int64

In [7]:
df.dtypes

itching                  int64
skin_rash                int64
nodal_skin_eruptions     int64
continuous_sneezing      int64
shivering                int64
                         ...
inflammatory_nails       int64
blister                  int64
red_sore_around_nose     int64
yellow_crust_ooze        int64
prognosis               object
Length: 133, dtype: object

## Initial Data Exploration

In [9]:
dataset.head(3)

,itching,skin_rash,nodal_skin_eruptions,continuous_sneezing,shivering,chills,joint_pain,stomach_pain,acidity,ulcers_on_tongue,...,blackheads,scurring,skin_peeling,silver_like_dusting,small_dents_in_nails,inflammatory_nails,blister,red_sore_around_nose,yellow_crust_ooze,prognosis
0,1,1,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,Fungal infection
1,0,1,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,Fungal infection
2,1,0,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,Fungal infection

In [10]:
dataset.shape

(4920, 133)

In [11]:
dataset['prognosis'].unique()

array(['Fungal infection', 'Allergy', 'GERD', 'Chronic cholestasis',
       'Drug Reaction', 'Peptic ulcer diseae', 'AIDS', 'Diabetes ',
       'Gastroenteritis', 'Bronchial Asthma', 'Hypertension ', 'Migraine',
       'Cervical spondylosis', 'Paralysis (brain hemorrhage)', 'Jaundice',
       'Malaria', 'Chicken pox', 'Dengue', 'Typhoid', 'hepatitis A',
       'Hepatitis B', 'Hepatitis C', 'Hepatitis D', 'Hepatitis E',
       'Alcoholic hepatitis', 'Tuberculosis', 'Common Cold', 'Pneumonia',
       'Dimorphic hemmorhoids(piles)', 'Heart attack', 'Varicose veins',
       'Hypothyroidism', 'Hyperthyroidism', 'Hypoglycemia',
       'Osteoarthristis', 'Arthritis',
       '(vertigo) Paroymsal  Positional Vertigo', 'Acne',
       'Urinary tract infection', 'Psoriasis', 'Impetigo'], dtype=object)

## Dataset Information and Data Types

In [12]:
dataset.columns

Index(['itching', 'skin_rash', 'nodal_skin_eruptions', 'continuous_sneezing',
       'shivering', 'chills', 'joint_pain', 'stomach_pain', 'acidity',
       'ulcers_on_tongue',
       ...
       'blackheads', 'scurring', 'skin_peeling', 'silver_like_dusting',
       'small_dents_in_nails', 'inflammatory_nails', 'blister',
       'red_sore_around_nose', 'yellow_crust_ooze', 'prognosis'],
      dtype='object', length=133)

In [13]:
dataset.dtypes

itching                  int64
skin_rash                int64
nodal_skin_eruptions     int64
continuous_sneezing      int64
shivering                int64
                         ...
inflammatory_nails       int64
blister                  int64
red_sore_around_nose     int64
yellow_crust_ooze        int64
prognosis               object
Length: 133, dtype: object

In [14]:
df["prognosis"].value_counts()

prognosis
Fungal infection                           120
Allergy                                    120
GERD                                       120
Chronic cholestasis                        120
Drug Reaction                              120
Peptic ulcer diseae                        120
AIDS                                       120
Diabetes                                   120
Gastroenteritis                            120
Bronchial Asthma                           120
Hypertension                               120
Migraine                                   120
Cervical spondylosis                       120
Paralysis (brain hemorrhage)               120
Jaundice                                   120
Malaria                                    120
Chicken pox                                120
Dengue                                     120
Typhoid                                    120
hepatitis A                                120
Hepatitis B                                120
Hepatitis C                                120
Hepatitis D                                120
Hepatitis E                                120
Alcoholic hepatitis                        120
Tuberculosis                               120
Common Cold                                120
Pneumonia                                  120
Dimorphic hemmorhoids(piles)               120
Heart attack                               120
Varicose veins                             120
Hypothyroidism                             120
Hyperthyroidism                            120
Hypoglycemia                               120
Osteoarthristis                            120
Arthritis                                  120
(vertigo) Paroymsal  Positional Vertigo    120
Acne                                       120
Urinary tract infection                    120
Psoriasis                                  120
Impetigo                                   120
Name: count, dtype: int64

## Checking for Missing Values

In [15]:
dataset.isnull().sum()

itching                 0
skin_rash               0
nodal_skin_eruptions    0
continuous_sneezing     0
shivering               0
                       ..
inflammatory_nails      0
blister                 0
red_sore_around_nose    0
yellow_crust_ooze       0
prognosis               0
Length: 133, dtype: int64

## Data Cleaning and Preprocessing

In [16]:
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder

### Feature Selection and Target Variable Definition

In [17]:
X = dataset.drop('prognosis',axis=1)
Y = dataset['prognosis']

In [18]:
le = LabelEncoder()
le.fit(Y)
Y=le.transform(Y)

In [19]:
X

,itching,skin_rash,nodal_skin_eruptions,continuous_sneezing,shivering,chills,joint_pain,stomach_pain,acidity,ulcers_on_tongue,...,pus_filled_pimples,blackheads,scurring,skin_peeling,silver_like_dusting,small_dents_in_nails,inflammatory_nails,blister,red_sore_around_nose,yellow_crust_ooze
0,1,1,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,0,1,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,1,0,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,1,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,1,1,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4915,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4916,0,1,0,0,0,0,0,0,0,0,...,1,1,1,0,0,0,0,0,0,0
4917,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4918,0,1,0,0,0,0,1,0,0,0,...,0,0,0,1,1,1,1,0,0,0
4919,0,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,1,1,1

In [20]:
Y

array([15, 15, 15, ..., 38, 35, 27], shape=(4920,))

## Splitting Data into Training and Testing Sets

In [21]:
X_train,X_test,Y_train,Y_test=train_test_split(X,Y,test_size=0.3,random_state=20)

In [22]:
X_train.shape,X_test.shape,Y_train.shape,Y_test.shape

((3444, 132), (1476, 132), (3444,), (1476,))

## Machine Learning Model Selection

In [23]:
# Grdient Boosting

In [24]:
from sklearn.datasets import make_classification
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier,GradientBoostingClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.naive_bayes import MultinomialNB

from sklearn.metrics import accuracy_score,confusion_matrix
import numpy as np

#craeting a dictionary to store models

models={
    'SVC':SVC(kernel='linear'),
    'RandomForestClassifier':RandomForestClassifier(n_estimators=100,random_state=42),
    'GradientBoostingClassifier':GradientBoostingClassifier(n_estimators=100,random_state=42),
    'KNeighborsClassifier':KNeighborsClassifier(n_neighbors=5),
    'MultinomialNB':MultinomialNB()
}
for model_name,model in models.items():
    model.fit(X_train,Y_train)   #<--train model

    predictions = model.predict(X_test)   #<--test model

    accuracy = accuracy_score(Y_test,predictions)   #<--calculating accuracy of model

    cm = confusion_matrix(Y_test,predictions)  #<--calculating confusion matrix

    print(f'{model_name} accuracy: {accuracy}')
    print(f'{model_name} confusion_matrix: ')
    print(np.array2string(cm,separator=','))

SVC accuracy: 1.0
SVC confusion_matrix:
[[40, 0, 0,..., 0, 0, 0],
 [ 0,43, 0,..., 0, 0, 0],
 [ 0, 0,28,..., 0, 0, 0],
 ...,
 [ 0, 0, 0,...,34, 0, 0],
 [ 0, 0, 0,..., 0,41, 0],
 [ 0, 0, 0,..., 0, 0,31]]
RandomForestClassifier accuracy: 1.0
RandomForestClassifier confusion_matrix:
[[40, 0, 0,..., 0, 0, 0],
 [ 0,43, 0,..., 0, 0, 0],
 [ 0, 0,28,..., 0, 0, 0],
 ...,
 [ 0, 0, 0,...,34, 0, 0],
 [ 0, 0, 0,..., 0,41, 0],
 [ 0, 0, 0,..., 0, 0,31]]
GradientBoostingClassifier accuracy: 1.0
GradientBoostingClassifier confusion_matrix:
[[40, 0, 0,..., 0, 0, 0],
 [ 0,43, 0,..., 0, 0, 0],
 [ 0, 0,28,..., 0, 0, 0],
 ...,
 [ 0, 0, 0,...,34, 0, 0],
 [ 0, 0, 0,..., 0,41, 0],
 [ 0, 0, 0,..., 0, 0,31]]
KNeighborsClassifier accuracy: 1.0
KNeighborsClassifier confusion_matrix:
[[40, 0, 0,..., 0, 0, 0],
 [ 0,43, 0,..., 0, 0, 0],
 [ 0, 0,28,..., 0, 0, 0],
 ...,
 [ 0, 0, 0,...,34, 0, 0],
 [ 0, 0, 0,..., 0,41, 0],
 [ 0, 0, 0,..., 0, 0,31]]
MultinomialNB accuracy: 1.0
MultinomialNB confusion_matrix:
[[40, 0, 0,..., 0, 0, 0],
 [ 0,43, 0,..., 0, 0, 0],
 [ 0, 0,28,..., 0, 0, 0],
 ...,
 [ 0, 0, 0,...,34, 0, 0],
 [ 0, 0, 0,..., 0,41, 0],
 [ 0, 0, 0,..., 0, 0,31]]

## Model Training

In [25]:
svc=SVC(kernel='linear')
svc.fit(X_train,Y_train)

SVC(kernel='linear')

## Making Predictions

In [26]:
ypred=svc.predict(X_test)

## Model Evaluation

In [27]:
accuracy_score(Y_test,ypred)

1.0

## Saving model

In [28]:
import pickle
import os

os.makedirs("model", exist_ok=True)

pickle.dump(svc, open("model/svc.pkl", "wb"))

## Load model

In [29]:
svc=pickle.load(open('model/svc.pkl','rb'))

In [30]:
X_test.iloc[0].values.reshape(1,-1)

array([[0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 1, 1, 1, 0, 1,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [31]:
#test 1
#the actual label has predicted the desies
print('PREDICTED LABEL :',svc.predict(X_test.iloc[0].values.reshape(1,-1)))
print('ACTUAL LABEL :',Y_test[0])

PREDICTED LABEL : [40]
ACTUAL LABEL : 40

c:\Users\91869\anaconda3\envs\cdac_project\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but SVC was fitted with feature names
  warnings.warn(

# recommendation system and prediction
load database and use logic for recommendations

In [32]:
sys_des = pd.read_csv('symtoms_df.csv')
precautions=pd.read_csv('precautions_df.csv')
workout=pd.read_csv('workout_df.csv')
description=pd.read_csv('description.csv')
medications=pd.read_csv('medications.csv')
diets=pd.read_csv('diets.csv')

In [33]:
diets

,Disease,Diet
0,Fungal infection,"['Antifungal Diet', 'Probiotics', 'Garlic', 'C..."
1,Allergy,"['Elimination Diet', 'Omega-3-rich foods', 'Vi..."
2,GERD,"['Low-Acid Diet', 'Fiber-rich foods', 'Ginger'..."
3,Chronic cholestasis,"['Low-Fat Diet', 'High-Fiber Diet', 'Lean prot..."
4,Drug Reaction,"['Antihistamine Diet', 'Omega-3-rich foods', '..."
5,Peptic ulcer disease,"['Low-Acid Diet', 'Fiber-rich foods', 'Ginger'..."
6,AIDS,"['Balanced Diet', 'Protein-rich foods', 'Fruit..."
7,Diabetes,"['Low-Glycemic Diet', 'Fiber-rich foods', 'Lea..."
8,Gastroenteritis,"['Bland Diet', 'Bananas', 'Rice', 'Applesauce'..."
9,Bronchial Asthma,"['Anti-Inflammatory Diet', 'Omega-3-rich foods..."
10,Hypertension,"['DASH Diet', 'Low-sodium foods', 'Fruits and ..."
11,Migraine,"['Migraine Diet', 'Low-Tyramine Diet', 'Caffei..."
12,Cervical spondylosis,"['Arthritis Diet', 'Anti-Inflammatory Diet', '..."
13,Paralysis (brain hemorrhage),"['Heart-Healthy Diet', 'Low-sodium foods', 'Fr..."
14,Jaundice,"['Liver-Healthy Diet', 'Low-fat Diet', 'Fruits..."
15,Malaria,"['Malaria Diet', 'Hydration', 'High-Calorie Di..."
16,Chicken pox,"['Chicken Pox Diet', 'High-Calorie Diet', 'Sof..."
17,Dengue,"['Dengue Diet', 'Hydration', 'High-Calorie Die..."
18,Typhoid,"['Typhoid Diet', 'High-Calorie Diet', 'Soft an..."
19,hepatitis A,"['Hepatitis A Diet', 'High-Calorie Diet', 'Sof..."
20,Hepatitis B,"['Hepatitis B Diet', 'High-Calorie Diet', 'Sof..."
21,Hepatitis C,"['Hepatitis C Diet', 'High-Calorie Diet', 'Sof..."
22,Hepatitis D,"['Hepatitis D Diet', 'High-Calorie Diet', 'Sof..."
23,Hepatitis E,"['Hepatitis E Diet', 'High-Calorie Diet', 'Sof..."
24,Alcoholic hepatitis,"['Liver-Healthy Diet', 'Low-fat Diet', 'Fruits..."
25,Tuberculosis,"['TB Diet', 'High-Calorie Diet', 'Soft and bla..."
26,Common Cold,"['Cold Diet', 'Hydration', 'Warm fluids', 'Res..."
27,Pneumonia,"['Pneumonia Diet', 'High-Calorie Diet', 'Soft ..."
28,Dimorphic hemmorhoids(piles),"['Hemorrhoids Diet', 'High-Fiber Diet', 'Hydra..."
29,Heart attack,"['Heart-Healthy Diet', 'Low-sodium foods', 'Fr..."
30,Varicose veins,"['Varicose Veins Diet', 'High-Fiber Diet', 'Fr..."
31,Hypothyroidism,"['Hypothyroidism Diet', 'Iodine-rich foods', '..."
32,Hyperthyroidism,"['Hyperthyroidism Diet', 'Low-Iodine Diet', 'C..."
33,Hypoglycemia,"['Hypoglycemia Diet', 'Complex carbohydrates',..."
34,Osteoarthristis,"['Arthritis Diet', 'Anti-Inflammatory Diet', '..."
35,Arthritis,"['Arthritis Diet', 'Anti-Inflammatory Diet', '..."
36,(vertigo) Paroymsal Positional Vertigo,"['Vertigo Diet', 'Low-Salt Diet', 'Hydration',..."
37,Acne,"['Acne Diet', 'Low-Glycemic Diet', 'Hydration'..."
38,Urinary tract infection,"['UTI Diet', 'Hydration', 'Cranberry juice', '..."
39,Psoriasis,"['Psoriasis Diet', 'Anti-Inflammatory Diet', '..."
40,Impetigo,"['Impetigo Diet', 'Antibiotic treatment', 'Fru..."

In [34]:
sys_des

,Unnamed: 0,Disease,Symptom_1,Symptom_2,Symptom_3,Symptom_4
0,0,Fungal infection,itching,skin_rash,nodal_skin_eruptions,dischromic _patches
1,1,Fungal infection,skin_rash,nodal_skin_eruptions,dischromic _patches,NaN
2,2,Fungal infection,itching,nodal_skin_eruptions,dischromic _patches,NaN
3,3,Fungal infection,itching,skin_rash,dischromic _patches,NaN
4,4,Fungal infection,itching,skin_rash,nodal_skin_eruptions,NaN
...,...,...,...,...,...,...
4915,4915,(vertigo) Paroymsal Positional Vertigo,vomiting,headache,nausea,spinning_movements
4916,4916,Acne,skin_rash,pus_filled_pimples,blackheads,scurring
4917,4917,Urinary tract infection,burning_micturition,bladder_discomfort,foul_smell_of urine,continuous_feel_of_urine
4918,4918,Psoriasis,skin_rash,joint_pain,skin_peeling,silver_like_dusting
4919,4919,Impetigo,skin_rash,high_fever,blister,red_sore_around_nose

In [35]:
def helper(dis):
    desc = description[description['Disease'] == predicted_disease]['Description']
    desc = " ".join([w for w in desc])

    pre = precautions[precautions['Disease'] == dis][['Precaution_1', 'Precaution_2', 'Precaution_3', 'Precaution_4']]
    pre = [col for col in pre.values]

    med = medications[medications['Disease'] == dis]['Medication']
    med = [med for med in med.values]

    die = diets[diets['Disease'] == dis]['Diet']
    die = [die for die in die.values]

    wrkout = workout[workout['disease'] == dis] ['workout']

    return desc,pre,med,die,wrkout

symptoms_dict = {'itching': 0, 'skin_rash': 1, 'nodal_skin_eruptions': 2, 'continuous_sneezing': 3, 'shivering': 4, 'chills': 5, 'joint_pain': 6, 'stomach_pain': 7, 'acidity': 8, 'ulcers_on_tongue': 9, 'muscle_wasting': 10, 'vomiting': 11, 'burning_micturition': 12, 'spotting_ urination': 13, 'fatigue': 14, 'weight_gain': 15, 'anxiety': 16, 'cold_hands_and_feets': 17, 'mood_swings': 18, 'weight_loss': 19, 'restlessness': 20, 'lethargy': 21, 'patches_in_throat': 22, 'irregular_sugar_level': 23, 'cough': 24, 'high_fever': 25, 'sunken_eyes': 26, 'breathlessness': 27, 'sweating': 28, 'dehydration': 29, 'indigestion': 30, 'headache': 31, 'yellowish_skin': 32, 'dark_urine': 33, 'nausea': 34, 'loss_of_appetite': 35, 'pain_behind_the_eyes': 36, 'back_pain': 37, 'constipation': 38, 'abdominal_pain': 39, 'diarrhoea': 40, 'mild_fever': 41, 'yellow_urine': 42, 'yellowing_of_eyes': 43, 'acute_liver_failure': 44, 'fluid_overload': 45, 'swelling_of_stomach': 46, 'swelled_lymph_nodes': 47, 'malaise': 48, 'blurred_and_distorted_vision': 49, 'phlegm': 50, 'throat_irritation': 51, 'redness_of_eyes': 52, 'sinus_pressure': 53, 'runny_nose': 54, 'congestion': 55, 'chest_pain': 56, 'weakness_in_limbs': 57, 'fast_heart_rate': 58, 'pain_during_bowel_movements': 59, 'pain_in_anal_region': 60, 'bloody_stool': 61, 'irritation_in_anus': 62, 'neck_pain': 63, 'dizziness': 64, 'cramps': 65, 'bruising': 66, 'obesity': 67, 'swollen_legs': 68, 'swollen_blood_vessels': 69, 'puffy_face_and_eyes': 70, 'enlarged_thyroid': 71, 'brittle_nails': 72, 'swollen_extremeties': 73, 'excessive_hunger': 74, 'extra_marital_contacts': 75, 'drying_and_tingling_lips': 76, 'slurred_speech': 77, 'knee_pain': 78, 'hip_joint_pain': 79, 'muscle_weakness': 80, 'stiff_neck': 81, 'swelling_joints': 82, 'movement_stiffness': 83, 'spinning_movements': 84, 'loss_of_balance': 85, 'unsteadiness': 86, 'weakness_of_one_body_side': 87, 'loss_of_smell': 88, 'bladder_discomfort': 89, 'foul_smell_of urine': 90, 'continuous_feel_of_urine': 91, 'passage_of_gases': 92, 'internal_itching': 93, 'toxic_look_(typhos)': 94, 'depression': 95, 'irritability': 96, 'muscle_pain': 97, 'altered_sensorium': 98, 'red_spots_over_body': 99, 'belly_pain': 100, 'abnormal_menstruation': 101, 'dischromic _patches': 102, 'watering_from_eyes': 103, 'increased_appetite': 104, 'polyuria': 105, 'family_history': 106, 'mucoid_sputum': 107, 'rusty_sputum': 108, 'lack_of_concentration': 109, 'visual_disturbances': 110, 'receiving_blood_transfusion': 111, 'receiving_unsterile_injections': 112, 'coma': 113, 'stomach_bleeding': 114, 'distention_of_abdomen': 115, 'history_of_alcohol_consumption': 116, 'fluid_overload.1': 117, 'blood_in_sputum': 118, 'prominent_veins_on_calf': 119, 'palpitations': 120, 'painful_walking': 121, 'pus_filled_pimples': 122, 'blackheads': 123, 'scurring': 124, 'skin_peeling': 125, 'silver_like_dusting': 126, 'small_dents_in_nails': 127, 'inflammatory_nails': 128, 'blister': 129, 'red_sore_around_nose': 130, 'yellow_crust_ooze': 131}
diseases_list = {15: 'Fungal infection', 4: 'Allergy', 16: 'GERD', 9: 'Chronic cholestasis', 14: 'Drug Reaction', 33: 'Peptic ulcer diseae', 1: 'AIDS', 12: 'Diabetes ', 17: 'Gastroenteritis', 6: 'Bronchial Asthma', 23: 'Hypertension ', 30: 'Migraine', 7: 'Cervical spondylosis', 32: 'Paralysis (brain hemorrhage)', 28: 'Jaundice', 29: 'Malaria', 8: 'Chicken pox', 11: 'Dengue', 37: 'Typhoid', 40: 'hepatitis A', 19: 'Hepatitis B', 20: 'Hepatitis C', 21: 'Hepatitis D', 22: 'Hepatitis E', 3: 'Alcoholic hepatitis', 36: 'Tuberculosis', 10: 'Common Cold', 34: 'Pneumonia', 13: 'Dimorphic hemmorhoids(piles)', 18: 'Heart attack', 39: 'Varicose veins', 26: 'Hypothyroidism', 24: 'Hyperthyroidism', 25: 'Hypoglycemia', 31: 'Osteoarthristis', 5: 'Arthritis', 0: '(vertigo) Paroymsal  Positional Vertigo', 2: 'Acne', 38: 'Urinary tract infection', 35: 'Psoriasis', 27: 'Impetigo'}

#model prediction function

def get_predicted_value(patient_symptoms):
    input_vector = np.zeros(len(symptoms_dict))

    for item in patient_symptoms:
        input_vector[symptoms_dict[item]]=1
    return diseases_list[svc.predict([input_vector])[0]]

In [36]:
#test 1:
symptoms=input('ENTER YOUR SYMPTOMS...')
user_symptoms=[s.strip() for s in symptoms.split(',')]
user_symptoms=[sym.strip("[]' ") for sym in user_symptoms]
predicted_disease=get_predicted_value(user_symptoms)
desc,pre,med,die,wrkout = helper(predicted_disease)

#results print
print('**********************PREDICTED DISEASE*************************')
print(predicted_disease)
print('**********************DESCRIPTION*******************************')
print(desc)
print('**********************PRECAUTIONS*******************************')
i=1
for p_i in pre[0]:
    print(i,':',p_i)
    i+=1
print('**********************MEDICATIONS*******************************')
i=1
for m_i in med:
    print(i,':',m_i)
    i+=1  
print('**********************WORKOUT*******************************')
i=1
for w_i in wrkout:
    print(i,':',w_i)
    i+=1 
print('**********************DIET*******************************')
i=1
for d in die:
    print(i,':',d)
    i+=1

**********************PREDICTED DISEASE*************************
Fungal infection
**********************DESCRIPTION*******************************
Fungal infection is a common skin condition caused by fungi.
**********************PRECAUTIONS*******************************
1 : bath twice
2 : use detol or neem in bathing water
3 : keep infected area dry
4 : use clean cloths
**********************MEDICATIONS*******************************
1 : ['Antifungal Cream', 'Fluconazole', 'Terbinafine', 'Clotrimazole', 'Ketoconazole']
**********************WORKOUT*******************************
1 : Avoid sugary foods
2 : Consume probiotics
3 : Increase intake of garlic
4 : Include yogurt in diet
5 : Limit processed foods
6 : Stay hydrated
7 : Consume green tea
8 : Eat foods rich in zinc
9 : Include turmeric in diet
10 : Eat fruits and vegetables
**********************DIET*******************************
1 : ['Antifungal Diet', 'Probiotics', 'Garlic', 'Coconut oil', 'Turmeric']

c:\Users\91869\anaconda3\envs\cdac_project\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but SVC was fitted with feature names
  warnings.warn(